[workspace]
members = ["crates/2015/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[profile.dev]
debug = 0
incremental = true
strip = "symbols"

[profile.release]
lto = "thin"
debug = 0
strip = "symbols"
panic = "abort"
codegen-units = 1
