[package]
name = "aoc-2015-2"
version = "0.0.0"
authors = ["Filip Andersson"]
description = "Advent of code 2015, day 2"
license = "MIT"
edition = "2021"

[lib]
doctest = false

[dependencies]
helper = { workspace = true }
itertools = { workspace = true }
anyhow = { workspace = true }
