[package]
name = "aoc-2015-3"
version = "0.0.0"
authors = ["Filip Andersson"]
description = "Advent of code 2015, day 3"
license = "MIT"
edition = "2021"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
