[package]
name = "aoc-2015-7"
version = "0.0.0"
authors = ["Filip Andersson"]
description = "Advent of code 2015, day 7"
license = "MIT"
edition = "2021"

[lib]
doctest = false

[dependencies]
itertools = { workspace = true }
anyhow = { workspace = true }